# Generated by Django 3.2.20 on 2023-08-10 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='readstatus',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to=settings.AUTH_USER_MODEL, verbose_name='Читатель'),
        ),
        migrations.AddField(
            model_name='post',
            name='blog',
            field=models.ForeignKey(help_text='Блог, к которому относится пост', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blogs.blog', verbose_name='Блог'),
        ),
        migrations.AddField(
            model_name='follow',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='blogs.blog', verbose_name='Блог'),
        ),
        migrations.AddField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик'),
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.OneToOneField(help_text='Введите автора блога', on_delete=django.db.models.deletion.CASCADE, related_name='blog', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'blog'), name='Проверка повторной подписки'),
        ),
    ]
